In [1]:
from sklearn.datasets import load_iris
import pandas as pd

In [2]:
# Load iris dataset from ScikitLearn using load_iris(). 
# Assign the dataset to X and the target values to y.

In [5]:
iris = load_iris()

In [9]:
# Print the dataset keys using iris_dataset.keys()

In [10]:
iris.keys()


dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [11]:
# Print the names of the categories in the target file

In [12]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [13]:
# Print the feature names in the Iris dataset

In [14]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [15]:
# Print the type of the Iris dataset.

In [16]:
type(iris.data)

numpy.ndarray

In [17]:
# Print the shape of the Iris dataset.

In [18]:
iris.data.shape

(150, 4)

In [19]:
# Print the first five rows of the Iris dataset.

In [20]:
iris.data[:5,:]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [21]:
# Print the type of the target variable of Iris dataset.

In [22]:
type(iris.target)

numpy.ndarray

In [23]:
# Print the shape of the target variable of Iris dataset.

In [24]:
iris.target.shape

(150,)

In [25]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [26]:
# Import NumPy with import numpy as np and use the numpy.unique() 
# function to print the unique values of the target variable of Iris dataset

In [29]:
import numpy as np
np.unique(iris.target)

array([0, 1, 2])

In [30]:
# Split dataset into train and test datasets using from 
# sklearn.model_selection import train_test_split

In [32]:
from sklearn.model_selection import train_test_split
x = iris.data
y = iris.target

train_x, test_x, train_y, test_y = train_test_split(x,y,test_size=0.25, random_state=1)

In [34]:
# Print the shape of train/test datasets and the train/test target variables.

In [35]:
train_x.shape, test_x.shape, train_y.shape, test_y.shape

((112, 4), (38, 4), (112,), (38,))

In [8]:
# Build your K-neighbors classifier for nearest neighbor of 1 using from 
# sklearn.neighbors import KNeighborsClassifier, fit the model to your train 
# dataset and make a prediction for teh data point of [5, 1.9, 1, 0.2]. 
# Print your prediction class value as an integer and also the corresponding 
# string label.

In [38]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=1)
knn.fit(train_x, train_y)
data_point = [[5, 1.9, 1, 0.2]]
prediction = knn.predict(data_point)
iris.target_names[prediction[0]]

'setosa'