In [1]:
# 1- Create three lists representing house features, each list containing ten values. The first one for the house's 
# size in square meters, the second one for rooms and last for price. Then, create an array combining these lists.

In [2]:
import numpy as np
size = [120, 85, 70, 210, 100, 190, 75, 160, 130, 110]
room = [5, 3, 3, 7, 4, 6, 2, 5, 4, 3]
price = [300, 200, 180, 500, 250, 450, 150, 400, 275, 230]
feature = np.array([size,room,price])
feature

array([[120,  85,  70, 210, 100, 190,  75, 160, 130, 110],
       [  5,   3,   3,   7,   4,   6,   2,   5,   4,   3],
       [300, 200, 180, 500, 250, 450, 150, 400, 275, 230]])

In [3]:
# 2- Transpose the array you have created, so that every line can represent features of one house.

In [4]:
feature = feature.T
feature

array([[120,   5, 300],
       [ 85,   3, 200],
       [ 70,   3, 180],
       [210,   7, 500],
       [100,   4, 250],
       [190,   6, 450],
       [ 75,   2, 150],
       [160,   5, 400],
       [130,   4, 275],
       [110,   3, 230]])

In [5]:
# 3- Display the shape of the array and explain what it means.
# For the following assignment, you are going to use Earthquakes dataset.

In [6]:
feature.shape # 10 rows, 3 columns

(10, 3)

In [7]:
# 4- Load the Earthquakes dataset. Export the dataset to an array as you covered in the previous lesson.

In [8]:
import pandas as pd
df = pd.read_csv("earthquakes1970-2014.csv")
df_np = df.values
df_np

array([['1970/01/04 17:00:40.20', 24.1389999999999, 102.503, ..., 0.0,
        'NEI', 1970010440.0],
       ['1970/01/06 05:35:51.80', -9.628, 151.458, ..., 0.0, 'NEI',
        1970010640.0],
       ['1970/01/08 17:12:39.10', -34.741, 178.568, ..., 0.0, 'NEI',
        1970010840.0],
       ...,
       ['2013/12/17 23:38:08.10', 20.7635, 146.759899999999, ..., 0.74,
        'us', 2013121720.0],
       ['2014/01/01 16:03:28.89', -13.8779, 167.2434, ..., 0.67, 'us',
        2014010120.0],
       ['2014/01/13 04:01:04.69', 19.0014, -66.8478, ..., 1.42, 'us',
        2014011320.0]], dtype=object)

In [9]:
# 5- Slice first 20 rows and column numbers 3, 5, 6, 7, 12. Then, assign the array you sliced to a variable.

In [10]:
array = df_np[:20,[1,2, 3, 4, 11]]
array

array([[24.1389999999999, 102.503, 31.0, 7.5, 1970010440.0],
       [-9.628, 151.458, 8.0, 6.2, 1970010640.0],
       [-34.741, 178.568, 179.0, 6.1, 1970010840.0],
       [6.825, 126.736999999999, 73.0, 6.1, 1970011040.0],
       [60.28, -152.66, 85.0, 6.0, nan],
       [-25.8, -177.348999999999, 80.0, 6.5, 1970012040.0],
       [42.518999999999906, 142.966, 46.0, 6.4, 1970012040.0],
       [7.017, -104.298, 33.0, 6.6, 1970012140.0],
       [-12.579, 166.37, 50.0, 6.4, 1970012640.0],
       [15.532, -99.48399999999991, 21.0, 6.5, 1970020440.0],
       [12.598, 122.117, 11.0, 6.6, 1970020540.0],
       [23.096, 100.775, 33.0, 6.1, 1970020640.0],
       [30.576, 103.031, 33.0, 6.0, 1970022440.0],
       [50.13, -179.5898, 7.0, 6.0, nan],
       [52.589799999999904, -175.039999999999, 161.0, 6.1, nan],
       [12.134, 143.706999999999, 33.0, 6.2, 1970030440.0],
       [-19.0079999999999, 168.603, 41.0, 6.5, 1970030940.0],
       [44.798, 148.87, 40.0, 6.0, 1970031040.0],
       [57.39, -1

In [11]:
# 6- Display the row numbers where last values are equal to 4.5 or higher.

In [12]:
np.where(array[:,-1] >= 4.5)

C:\Users\hskay\AppData\Local\Temp\ipykernel_38612\3120884243.py:1: RuntimeWarning: invalid value encountered in greater_equal
  np.where(array[:,-1] >= 4.5)


(array([ 0,  1,  2,  3,  5,  6,  7,  8,  9, 10, 11, 12, 15, 16, 17, 19],
       dtype=int64),)

In [13]:
# 7- Assign 1 to first row.

In [14]:
array[0,:] = 1
array

array([[1, 1, 1, 1, 1],
       [-9.628, 151.458, 8.0, 6.2, 1970010640.0],
       [-34.741, 178.568, 179.0, 6.1, 1970010840.0],
       [6.825, 126.736999999999, 73.0, 6.1, 1970011040.0],
       [60.28, -152.66, 85.0, 6.0, nan],
       [-25.8, -177.348999999999, 80.0, 6.5, 1970012040.0],
       [42.518999999999906, 142.966, 46.0, 6.4, 1970012040.0],
       [7.017, -104.298, 33.0, 6.6, 1970012140.0],
       [-12.579, 166.37, 50.0, 6.4, 1970012640.0],
       [15.532, -99.48399999999991, 21.0, 6.5, 1970020440.0],
       [12.598, 122.117, 11.0, 6.6, 1970020540.0],
       [23.096, 100.775, 33.0, 6.1, 1970020640.0],
       [30.576, 103.031, 33.0, 6.0, 1970022440.0],
       [50.13, -179.5898, 7.0, 6.0, nan],
       [52.589799999999904, -175.039999999999, 161.0, 6.1, nan],
       [12.134, 143.706999999999, 33.0, 6.2, 1970030440.0],
       [-19.0079999999999, 168.603, 41.0, 6.5, 1970030940.0],
       [44.798, 148.87, 40.0, 6.0, 1970031040.0],
       [57.39, -153.97, 16.0, 6.5, nan],
       [-29.6

In [15]:
# 8- Save the final state of the array to disk. You are going to use this in the next assignment.

In [16]:
np.save('data',array)

In [17]:
# 9- Load the array you saved in the previous lesson from the disk.

In [18]:
array2 = np.load('data.npy',allow_pickle=True)
array2

array([[1, 1, 1, 1, 1],
       [-9.628, 151.458, 8.0, 6.2, 1970010640.0],
       [-34.741, 178.568, 179.0, 6.1, 1970010840.0],
       [6.825, 126.736999999999, 73.0, 6.1, 1970011040.0],
       [60.28, -152.66, 85.0, 6.0, nan],
       [-25.8, -177.348999999999, 80.0, 6.5, 1970012040.0],
       [42.518999999999906, 142.966, 46.0, 6.4, 1970012040.0],
       [7.017, -104.298, 33.0, 6.6, 1970012140.0],
       [-12.579, 166.37, 50.0, 6.4, 1970012640.0],
       [15.532, -99.48399999999991, 21.0, 6.5, 1970020440.0],
       [12.598, 122.117, 11.0, 6.6, 1970020540.0],
       [23.096, 100.775, 33.0, 6.1, 1970020640.0],
       [30.576, 103.031, 33.0, 6.0, 1970022440.0],
       [50.13, -179.5898, 7.0, 6.0, nan],
       [52.589799999999904, -175.039999999999, 161.0, 6.1, nan],
       [12.134, 143.706999999999, 33.0, 6.2, 1970030440.0],
       [-19.0079999999999, 168.603, 41.0, 6.5, 1970030940.0],
       [44.798, 148.87, 40.0, 6.0, 1970031040.0],
       [57.39, -153.97, 16.0, 6.5, nan],
       [-29.6

In [19]:
# 10- Display the mean and the standard deviation for each column.

In [20]:
array2 = array2.astype(float)
array2[np.isnan(array2)] = 0
np.mean(array2, axis = 0), np.std(array2, axis = 0)

(array([1.42537900e+01, 2.21156100e+01, 5.35000000e+01, 5.99000000e+00,
        1.47751447e+09]),
 array([2.95243490e+01, 1.38403635e+02, 4.84855649e+01, 1.16528966e+00,
        8.53043377e+08]))

In [21]:
# 11- Subtract 1, 25, 25, 10, 4 from columns in order. (Remember it can be dobe in one line of code.)

In [22]:
array2 -= np.array([1, 25, 25, 10, 4])
array2

array([[ 0.00000000e+00, -2.40000000e+01, -2.40000000e+01,
        -9.00000000e+00, -3.00000000e+00],
       [-1.06280000e+01,  1.26458000e+02, -1.70000000e+01,
        -3.80000000e+00,  1.97001064e+09],
       [-3.57410000e+01,  1.53568000e+02,  1.54000000e+02,
        -3.90000000e+00,  1.97001084e+09],
       [ 5.82500000e+00,  1.01737000e+02,  4.80000000e+01,
        -3.90000000e+00,  1.97001104e+09],
       [ 5.92800000e+01, -1.77660000e+02,  6.00000000e+01,
        -4.00000000e+00, -4.00000000e+00],
       [-2.68000000e+01, -2.02349000e+02,  5.50000000e+01,
        -3.50000000e+00,  1.97001204e+09],
       [ 4.15190000e+01,  1.17966000e+02,  2.10000000e+01,
        -3.60000000e+00,  1.97001204e+09],
       [ 6.01700000e+00, -1.29298000e+02,  8.00000000e+00,
        -3.40000000e+00,  1.97001214e+09],
       [-1.35790000e+01,  1.41370000e+02,  2.50000000e+01,
        -3.60000000e+00,  1.97001264e+09],
       [ 1.45320000e+01, -1.24484000e+02, -4.00000000e+00,
        -3.50000000e+00

In [23]:
# 12- Multiply each element by 2. (Remember it can be done in one line of code.)

In [26]:
array2*=2
array2

array([[ 0.00000000e+00, -1.92000000e+02, -1.92000000e+02,
        -7.20000000e+01, -2.40000000e+01],
       [-8.50240000e+01,  1.01166400e+03, -1.36000000e+02,
        -3.04000000e+01,  1.57600851e+10],
       [-2.85928000e+02,  1.22854400e+03,  1.23200000e+03,
        -3.12000000e+01,  1.57600867e+10],
       [ 4.66000000e+01,  8.13896000e+02,  3.84000000e+02,
        -3.12000000e+01,  1.57600883e+10],
       [ 4.74240000e+02, -1.42128000e+03,  4.80000000e+02,
        -3.20000000e+01, -3.20000000e+01],
       [-2.14400000e+02, -1.61879200e+03,  4.40000000e+02,
        -2.80000000e+01,  1.57600963e+10],
       [ 3.32152000e+02,  9.43728000e+02,  1.68000000e+02,
        -2.88000000e+01,  1.57600963e+10],
       [ 4.81360000e+01, -1.03438400e+03,  6.40000000e+01,
        -2.72000000e+01,  1.57600971e+10],
       [-1.08632000e+02,  1.13096000e+03,  2.00000000e+02,
        -2.88000000e+01,  1.57601011e+10],
       [ 1.16256000e+02, -9.95872000e+02, -3.20000000e+01,
        -2.80000000e+01